# Generated by Django 2.0.4 on 2018-04-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('indicador', models.CharField(max_length=10)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('Gestión', 'Gestión'), ('Desempeño', 'Desempeño')], max_length=15, null=True)),
                ('dimension', models.CharField(blank=True, max_length=144, null=True)),
                ('criterios_evaluacion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('#2ecc71', 'Satisfactorio'), ('#2ecc71', 'Regular'), ('#2ecc71', 'Pésimo')], max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='indicadores.Indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Subevidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('completada', models.BooleanField(default=False)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevidencias', to='indicadores.Evidencia')),
            ],
        ),
        migrations.AddField(
            model_name='evidencia',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='indicadores.Indicador'),
        ),
    ]
