# Generated by Django 2.0.4 on 2018-04-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
