# Generated by Django 2.0.4 on 2018-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_auto_20180416_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
