# Generated by Django 2.0.4 on 2018-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_auto_20180416_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidencia',
            old_name='porcentaje',
            new_name='porcentaje_real',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='porcentaje_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
