# Generated by Django 2.0.4 on 2018-04-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0005_auto_20180416_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='status',
            field=models.CharField(choices=[('Satisfactorio', 'Satisfactorio'), ('Regular', 'Regular'), ('Pésimo', 'Pésimo')], max_length=15),
        ),
    ]
