# Generated by Django 2.0.4 on 2018-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0006_auto_20180417_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AddField(
            model_name='indicador',
            name='metodo_calculo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
