# Generated by Django 2.0.4 on 2018-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0007_auto_20180423_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/archivos/'),
        ),
    ]
