# Generated by Django 2.0.4 on 2018-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0008_indicador_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='status',
            field=models.CharField(choices=[('Satisfactorio', 'Satisfactorio'), ('Regular', 'Regular'), ('No satisfactorio', 'No satisfactorio')], max_length=15),
        ),
    ]
