# Generated by Django 2.0.4 on 2018-07-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0009_auto_20180723_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='status',
            field=models.CharField(choices=[('Satisfactorio', 'Satisfactorio'), ('Regular', 'Regular'), ('Insatisfactorio', 'Insatisfactorio')], max_length=15),
        ),
    ]
