# Generated by Django 2.0.4 on 2018-07-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0010_auto_20180723_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='status',
            field=models.CharField(choices=[('Satisfactorio', 'Satisfactorio'), ('Regular', 'Regular'), ('Insatisfactorio', 'Insatisfactorio'), ('NCS', 'NCS')], max_length=15),
        ),
    ]
